(() => {
  "use strict";
  const LG = window.LittleGod = {};

  LG.WORLD = Object.freeze({ width: 960, height: 600, fixedStepMs: 50, yearsPerStep: 0.002, maxPatches: 56, maxAnimals: 180, maxCarcasses: 80, missionYears: 8, trendWindowYears: 0.3 });
  LG.SEASONS = Object.freeze({ spring:{label:"春季",color:"#f4dc8b"}, summer:{label:"夏季",color:"#ffe6a6"}, autumn:{label:"秋季",color:"#f6c889"}, winter:{label:"冬季",color:"#d5effa"} });
  LG.PATCH = Object.freeze({ maxGreen:125,maxDry:82,maxSeeds:82,springGrowth:96,summerGrowth:66,autumnGrowth:24,mildGrowth:55,springGermination:30,winterWither:104,autumnSeedRate:.34,seedDecay:.012,dryDecaySpring:1.05,dryDecayOther:.34,fertilityGain:.0007,fertilityCost:.00045,litterSuppression:.38 });
  LG.SPECIES = Object.freeze({
    flora:{label:"草地",placementCount:1,color:"#68ad7d"},
    grazer:{label:"食草兽",placementCount:3,color:"#e9b554",walkSpeed:185,sprintSpeed:325,maxEnergy:108,baseDrain:11.5,sprintDrain:3.4,winterDrain:1.14,eatRate:42,greenEnergy:1.08,dryEnergy:.48,senseRadius:320,threatRadius:125,staminaMax:100,staminaDrain:76,staminaRecovery:48,minReproductionAge:1,elderAgeRatio:.88,reproductionEnergy:56,reproductionCost:14,reproductionCooldown:.28,lifespan:[10,15]},
    hunter:{label:"猎食兽",placementCount:1,color:"#8065ad",walkSpeed:175,chaseSpeed:370,maxEnergy:132,baseDrain:9.5,chaseDrain:2.4,winterDrain:1.1,preyEnergy:95,carrionEnergy:1,senseRadius:335,staminaMax:110,staminaDrain:58,staminaRecovery:32,minReproductionAge:1.8,elderAgeRatio:.88,reproductionEnergy:75,reproductionCost:20,reproductionCooldown:.8,lungeDistance:45,lungeSpeed:510,attackCooldown:.16,restAfterMiss:.06,feedRest:.12,lifespan:[14,20]}
  });

  LG.randomBetween=(min,max)=>min+Math.random()*(max-min);
  LG.clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  LG.distanceSquared=(a,b)=>{const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy;};
  LG.normalizeAngle=(angle)=>{while(angle>Math.PI)angle-=Math.PI*2;while(angle<-Math.PI)angle+=Math.PI*2;return angle;};
  LG.turnToward=(current,target,amount)=>current+LG.clamp(LG.normalizeAngle(target-current),-amount,amount);

  LG.freshLedger=(year=0)=>({year:Math.floor(year),grazerBirths:0,hunterBirths:0,grazerPredationDeaths:0,grazerStarvationDeaths:0,grazerOldAgeDeaths:0,hunterStarvationDeaths:0,hunterOldAgeDeaths:0,germinatedBiomass:0,greenConsumed:0,dryConsumed:0,carcassDecomposed:0,huntAttempts:0,huntSuccesses:0,huntFailures:0,seedDispersals:0,springRecoveries:0});
  LG.state={running:false,speed:1,selectedSpecies:"flora",year:0,coexistenceYears:0,longestCoexistence:0,historicalMissionComplete:false,season:"spring",patches:[],grazers:[],hunters:[],carcasses:[],rules:{growth:1,fertility:1,fullSeasons:true},events:[],effects:[],decor:[],pointer:{x:480,y:300,inside:false},nextEntityId:1,presence:{flora:false,grazer:false,hunter:false},trendBaseline:null,trendValues:{flora:"稳定",grazer:"稳定",hunter:"稳定"},ledger:LG.freshLedger(),lifetime:LG.freshLedger(),lastAnimalPlacementYear:-Infinity,minimumDuringAttempt:{grazers:Infinity,hunters:Infinity},springBaseline:null,springRecoveryYear:-1,eventFlags:{firstHunt:false,firstHunterBirth:false,firstSpringRecovery:false,grazerEndangered:false,hunterEndangered:false}};

  LG.incrementMetric=(key,amount=1)=>{LG.state.ledger[key]+=amount;LG.state.lifetime[key]+=amount;};
  LG.getResourceTotals=()=>LG.state.patches.reduce((t,p)=>{t.green+=p.green;t.dry+=p.dry;t.seeds+=p.seeds;t.fertility+=p.fertility;return t;},{green:0,dry:0,seeds:0,fertility:0});
  LG.hasDormantPlantLife=()=>{const t=LG.getResourceTotals();return t.green+t.dry+t.seeds>1;};
  LG.lifeStage=(animal)=>{const c=LG.SPECIES[animal.type];if(animal.age<c.minReproductionAge)return"juvenile";if(animal.age>=animal.lifespan*c.elderAgeRatio)return"elder";return"adult";};
  LG.getAgeStructure=(list)=>{const result={juvenile:0,adult:0,elder:0};for(const animal of list)result[LG.lifeStage(animal)]+=1;return result;};

  LG.createDecor=()=>{LG.state.decor=[];const colors=["rgba(239,231,178,.13)","rgba(91,151,121,.1)","rgba(99,153,172,.09)","rgba(255,255,255,.1)"];for(let i=0;i<22;i+=1)LG.state.decor.push({x:LG.randomBetween(20,940),y:LG.randomBetween(20,580),radiusX:LG.randomBetween(28,96),radiusY:LG.randomBetween(18,60),rotation:LG.randomBetween(0,Math.PI),color:colors[i%colors.length]});};
  LG.createPatch=(x,y,o={})=>{if(LG.state.patches.length>=LG.WORLD.maxPatches)return null;const p={id:LG.state.nextEntityId++,type:"flora",x:LG.clamp(x,42,918),y:LG.clamp(y,42,558),radius:o.radius??LG.randomBetween(32,47),green:LG.clamp(o.green??LG.randomBetween(68,96),0,LG.PATCH.maxGreen),dry:LG.clamp(o.dry??LG.randomBetween(7,15),0,LG.PATCH.maxDry),seeds:LG.clamp(o.seeds??LG.randomBetween(34,54),0,LG.PATCH.maxSeeds),fertility:LG.clamp(o.fertility??LG.randomBetween(.82,1.08),.35,1.3),phase:LG.randomBetween(0,Math.PI*2),spreadCooldown:LG.randomBetween(0,1),barrenAge:0};LG.state.patches.push(p);return p;};
  LG.findPatchNear=(x,y,radius=58)=>{let nearest=null,best=radius*radius;for(const p of LG.state.patches){const d=(p.x-x)**2+(p.y-y)**2;if(d<best){best=d;nearest=p;}}return nearest;};
  LG.seedPatchAt=(x,y)=>{const p=LG.findPatchNear(x,y,70);if(p){p.green=LG.clamp(p.green+28,0,LG.PATCH.maxGreen);p.dry=LG.clamp(p.dry+5,0,LG.PATCH.maxDry);p.seeds=LG.clamp(p.seeds+24,0,LG.PATCH.maxSeeds);return p;}return LG.createPatch(x,y);};
  LG.createAnimal=(type,x,y,o={})=>{if(LG.state.grazers.length+LG.state.hunters.length>=LG.WORLD.maxAnimals)return null;const c=LG.SPECIES[type],spread=o.spread??0;const a={id:LG.state.nextEntityId++,type,x:LG.clamp(x+LG.randomBetween(-spread,spread),14,946),y:LG.clamp(y+LG.randomBetween(-spread,spread),14,586),angle:LG.randomBetween(-Math.PI,Math.PI),age:o.age??LG.randomBetween(c.minReproductionAge*.45,c.minReproductionAge*1.8),energy:o.energy??LG.randomBetween(c.maxEnergy*.72,c.maxEnergy*.9),stamina:o.stamina??c.staminaMax,lifespan:o.lifespan??LG.randomBetween(c.lifespan[0],c.lifespan[1]),reproductionCooldown:o.reproductionCooldown??LG.randomBetween(.05,.45),attackCooldown:0,state:"wander",stateTimer:0,targetId:null,consecutiveFailures:0,wanderTimer:LG.randomBetween(.02,.16),bobPhase:LG.randomBetween(0,Math.PI*2),lastMealAge:o.lastMealAge??(type==="hunter"?1.3:0)};(type==="grazer"?LG.state.grazers:LG.state.hunters).push(a);return a;};
  LG.createCarcass=(x,y,sourceType,amount=30)=>{if(LG.state.carcasses.length>=LG.WORLD.maxCarcasses)LG.state.carcasses.shift();LG.state.carcasses.push({id:LG.state.nextEntityId++,x,y,sourceType,biomass:amount,age:0,maxAge:1.35});};

  LG.getPresence=()=>({flora:LG.hasDormantPlantLife(),grazer:LG.state.grazers.length>0,hunter:LG.state.hunters.length>0});
  LG.addEvent=(message,year=LG.state.year)=>{LG.state.events.unshift({id:`${year.toFixed(4)}-${LG.state.nextEntityId++}`,year,message});if(LG.state.events.length>14)LG.state.events.length=14;LG.renderEventLog?.();};
  LG.checkPresenceChanges=()=>{const current=LG.getPresence();for(const type of["flora","grazer","hunter"]){if(LG.state.presence[type]&&!current[type])LG.addEvent(`${type==="flora"?"草地生态（包括种子库）":LG.SPECIES[type].label}在世界中彻底灭绝。`);else if(!LG.state.presence[type]&&current[type]&&LG.state.year>.001)LG.addEvent(`${type==="flora"?"草地生态":LG.SPECIES[type].label}重新出现在世界中。`);}LG.state.presence=current;};

  LG.seedWorld=()=>{const s=LG.state;s.running=false;s.speed=1;s.year=0;s.coexistenceYears=0;s.longestCoexistence=0;s.historicalMissionComplete=false;s.season="spring";s.patches=[];s.grazers=[];s.hunters=[];s.carcasses=[];s.effects=[];s.events=[];s.nextEntityId=1;s.presence={flora:false,grazer:false,hunter:false};s.ledger=LG.freshLedger(0);s.lifetime=LG.freshLedger(0);s.lastAnimalPlacementYear=-Infinity;s.minimumDuringAttempt={grazers:Infinity,hunters:Infinity};s.springBaseline=null;s.springRecoveryYear=-1;s.eventFlags={firstHunt:false,firstHunterBirth:false,firstSpringRecovery:false,grazerEndangered:false,hunterEndangered:false};LG.createDecor();const centers=[[150,135],[340,105],[570,135],[790,120],[215,330],[470,290],[730,325],[130,500],[365,480],[610,495],[825,485]];for(const[x,y]of centers)LG.createPatch(x+LG.randomBetween(-25,25),y+LG.randomBetween(-20,20));for(let i=0;i<18;i+=1)LG.createAnimal("grazer",LG.randomBetween(110,850),LG.randomBetween(90,520),{age:LG.randomBetween(.35,2.4)});for(let i=0;i<2;i+=1)LG.createAnimal("hunter",LG.randomBetween(170,790),LG.randomBetween(120,480),{age:LG.randomBetween(1.9,3.6),energy:LG.randomBetween(104,122)});s.presence=LG.getPresence();s.trendBaseline=LG.buildTrendSnapshot?.()??null;s.minimumDuringAttempt={grazers:s.grazers.length,hunters:s.hunters.length};LG.addEvent("新的示范世界被创造：18只食草兽、2只猎食兽和11片草地等待时间开始。",0);LG.addEvent("创世命题：证明三层生态能够完成捕食、繁殖与春季恢复。",0);};
})();
