(() => {
  "use strict";
  const LG=window.LittleGod,{state:s,WORLD,SEASONS,PATCH,SPECIES}=LG;

  LG.findNearest=(source,targets,radius,predicate=null)=>{let nearest=null,best=radius*radius;for(const target of targets){if(predicate&&!predicate(target))continue;const d=LG.distanceSquared(source,target);if(d<best){best=d;nearest=target;}}return nearest;};
  LG.moveAnimal=(animal,desiredAngle,speed,dt)=>{animal.angle=LG.turnToward(animal.angle,desiredAngle,8*dt+.045);animal.x+=Math.cos(animal.angle)*speed*dt;animal.y+=Math.sin(animal.angle)*speed*dt;const margin=12;if(animal.x<margin||animal.x>WORLD.width-margin){animal.angle=Math.PI-animal.angle;animal.x=LG.clamp(animal.x,margin,WORLD.width-margin);}if(animal.y<margin||animal.y>WORLD.height-margin){animal.angle=-animal.angle;animal.y=LG.clamp(animal.y,margin,WORLD.height-margin);}};
  LG.wander=(animal,speed,dt)=>{animal.wanderTimer-=dt;if(animal.wanderTimer<=0){animal.angle+=LG.randomBetween(-1.2,1.2);animal.wanderTimer=LG.randomBetween(.035,.16);}LG.moveAnimal(animal,animal.angle,speed,dt);};
  LG.localPlantFood=(animal,radius=175)=>{const r2=radius*radius;let amount=0;for(const p of s.patches)if(LG.distanceSquared(animal,p)<=r2)amount+=p.green+p.dry*.35;return amount;};
  LG.reproductionSeasonMultiplier=()=>!s.rules.fullSeasons?1:s.season==="spring"?1.3:s.season==="summer"?.95:s.season==="autumn"?.18:0;

  LG.getSeason=()=>{if(!s.rules.fullSeasons)return"summer";const phase=((s.year%1)+1)%1;return phase<.25?"spring":phase<.5?"summer":phase<.75?"autumn":"winter";};
  LG.updateSeason=()=>{const next=LG.getSeason();if(next===s.season)return;s.season=next;const totals=LG.getResourceTotals();if(next==="spring")s.springBaseline={year:Math.floor(s.year),green:totals.green};if(next==="winter"&&Math.floor(s.year)===0)LG.addEvent("第一个冬季到来：鲜草将转为枯草，地下种子保持休眠。");};
  LG.rolloverLedgerIfNeeded=(previousYear)=>{const previousWhole=Math.floor(previousYear),currentWhole=Math.floor(s.year);if(currentWhole<=previousWhole)return;const births=s.ledger.grazerBirths+s.ledger.hunterBirths;const deaths=s.ledger.grazerPredationDeaths+s.ledger.grazerStarvationDeaths+s.ledger.grazerOldAgeDeaths+s.ledger.hunterStarvationDeaths+s.ledger.hunterOldAgeDeaths;if(births>0||deaths>0||s.ledger.huntAttempts>0)LG.addEvent(`第${currentWhole}年总结：出生${births}，死亡${deaths}，捕猎${s.ledger.huntSuccesses}/${s.ledger.huntAttempts}。`);s.ledger=LG.freshLedger(currentWhole);};

  function maybeDisperseSeed(p,dt){p.spreadCooldown=Math.max(0,p.spreadCooldown-dt);if(s.season!=="autumn"||p.spreadCooldown>0||p.seeds<46||p.green<58||s.patches.length>=WORLD.maxPatches||Math.random()>=.75*dt)return;const angle=LG.randomBetween(0,Math.PI*2),distance=LG.randomBetween(92,155),x=LG.clamp(p.x+Math.cos(angle)*distance,45,915),y=LG.clamp(p.y+Math.sin(angle)*distance,45,555);if(LG.findPatchNear(x,y,68))return;p.seeds-=16;LG.createPatch(x,y,{green:0,dry:0,seeds:16,fertility:LG.clamp(p.fertility*LG.randomBetween(.85,1.02),.4,1.2),radius:LG.randomBetween(25,34)});p.spreadCooldown=1.5;LG.incrementMetric("seedDispersals");if(s.lifetime.seedDispersals===1)LG.addEvent("第一批种子离开母草地，在空地形成新的休眠斑块。");}
  function updatePatch(p,dt){const multiplier=s.rules.growth,capacity=PATCH.maxGreen*(.68+p.fertility*.32),litter=LG.clamp(p.dry/PATCH.maxDry,0,1),crowding=LG.clamp(1-p.green/Math.max(1,capacity),0,1)*(1-litter*PATCH.litterSuppression);let growthRate=PATCH.mildGrowth;if(s.rules.fullSeasons)growthRate=s.season==="spring"?PATCH.springGrowth:s.season==="summer"?PATCH.summerGrowth:s.season==="autumn"?PATCH.autumnGrowth:0;let growthAdded=0;if(s.season==="spring"&&p.seeds>0&&p.green<capacity*.72){const germination=Math.min(p.seeds,PATCH.springGermination*multiplier*p.fertility*crowding*dt);p.seeds-=germination;p.green+=germination*.9;growthAdded+=germination*.9;LG.incrementMetric("germinatedBiomass",germination*.9);}if(growthRate>0&&(p.green>.15||p.seeds>.5)){const growth=growthRate*multiplier*p.fertility*crowding*dt;p.green+=growth;growthAdded+=growth;}if(s.season==="autumn"&&p.green>2){const seedGain=p.green*PATCH.autumnSeedRate*multiplier*dt;p.seeds=LG.clamp(p.seeds+seedGain,0,PATCH.maxSeeds);const dryGain=Math.min(p.green,p.green*.13*dt);p.green-=dryGain;p.dry=LG.clamp(p.dry+dryGain,0,PATCH.maxDry);}if(s.season==="winter"&&s.rules.fullSeasons&&p.green>0){const withered=Math.min(p.green,PATCH.winterWither*dt);p.green-=withered;p.dry=LG.clamp(p.dry+withered*.82,0,PATCH.maxDry);}const decayRate=s.season==="spring"?PATCH.dryDecaySpring:PATCH.dryDecayOther,dryDecay=Math.min(p.dry,p.dry*decayRate*dt);p.dry-=dryDecay;p.fertility=LG.clamp(p.fertility+dryDecay*PATCH.fertilityGain-growthAdded*PATCH.fertilityCost,.35,1.3);p.seeds=Math.max(0,p.seeds-p.seeds*PATCH.seedDecay*dt);p.green=LG.clamp(p.green,0,PATCH.maxGreen);p.dry=LG.clamp(p.dry,0,PATCH.maxDry);maybeDisperseSeed(p,dt);p.barrenAge=p.green+p.dry+p.seeds<.5?p.barrenAge+dt:0;}
  LG.updatePatches=(dt)=>{for(let i=s.patches.length-1;i>=0;i-=1){const p=s.patches[i];updatePatch(p,dt);if(p.barrenAge>1.5)s.patches.splice(i,1);}if(s.springBaseline&&s.springRecoveryYear!==s.springBaseline.year&&s.season==="spring"){const totals=LG.getResourceTotals();if(totals.green>=s.springBaseline.green+65){s.springRecoveryYear=s.springBaseline.year;LG.incrementMetric("springRecoveries");if(!s.eventFlags.firstSpringRecovery){s.eventFlags.firstSpringRecovery=true;LG.addEvent("草地第一次在冬季后完成明显春季恢复。");}}}};

  function chooseFoodPatch(grazer){let best=null,bestScore=-Infinity;for(const p of s.patches){const food=p.green+p.dry*.38;if(food<1)continue;const distance=Math.sqrt(LG.distanceSquared(grazer,p));if(distance>SPECIES.grazer.senseRadius)continue;const score=food*1.25-distance*.24;if(score>bestScore){bestScore=score;best=p;}}return best;}
  function grazerDensityPressure(){const totals=LG.getResourceTotals(),carrying=Math.max(10,totals.green/34+totals.dry/70);return LG.clamp(1-s.grazers.length/carrying,.08,1);}
  function hunterDensityPressure(){const sustainable=Math.max(1,s.grazers.length/7);return LG.clamp(1-s.hunters.length/(sustainable+1.2),.06,1);}
  function oldAgeDeathChance(animal,dt){const c=SPECIES[animal.type],elderStart=animal.lifespan*c.elderAgeRatio;if(animal.age<elderStart)return false;const progress=LG.clamp((animal.age-elderStart)/Math.max(.1,animal.lifespan-elderStart),0,1.5);if(animal.age>=animal.lifespan*1.32)return true;const health=animal.energy/c.maxEnergy;return Math.random()<( .06+progress*.46+(1-health)*.18)*dt;}
  function reproduce(parent,mate,type){const c=SPECIES[type];if(s.grazers.length+s.hunters.length>=WORLD.maxAnimals)return false;parent.energy-=c.reproductionCost;mate.energy-=c.reproductionCost*.35;parent.reproductionCooldown=c.reproductionCooldown;mate.reproductionCooldown=c.reproductionCooldown*.75;const child=LG.createAnimal(type,(parent.x+mate.x)/2,(parent.y+mate.y)/2,{spread:12,age:0,energy:c.maxEnergy*.55,stamina:c.staminaMax,reproductionCooldown:c.reproductionCooldown});if(!child)return false;LG.incrementMetric(type==="grazer"?"grazerBirths":"hunterBirths");s.effects.push({kind:"birth",x:child.x,y:child.y,age:0,color:c.color});if(type==="hunter"&&!s.eventFlags.firstHunterBirth){s.eventFlags.firstHunterBirth=true;LG.addEvent("猎食兽第一次产生后代，捕食层开始完成代际更新。");}return true;}
  function removeAnimal(collection,index,reason){const animal=collection[index];if(!animal)return;collection.splice(index,1);LG.createCarcass(animal.x,animal.y,animal.type,animal.type==="grazer"?26:34);const prefix=animal.type==="grazer"?"grazer":"hunter";if(reason==="starvation")LG.incrementMetric(`${prefix}StarvationDeaths`);if(reason==="oldAge")LG.incrementMetric(`${prefix}OldAgeDeaths`);if(reason==="predation")LG.incrementMetric("grazerPredationDeaths");}

  function attemptGrazerReproduction(dt){const c=SPECIES.grazer,season=LG.reproductionSeasonMultiplier();if(season<=0||s.grazers.length<2)return;const candidates=s.grazers.filter(a=>LG.lifeStage(a)==="adult"&&a.energy>=c.reproductionEnergy&&a.reproductionCooldown<=0&&LG.localPlantFood(a)>=48).sort((a,b)=>a.id-b.id);if(candidates.length<2)return;const boost=s.grazers.length<14?2:1;for(let i=0;i+1<candidates.length;i+=2){const probability=10.5*s.rules.fertility*season*grazerDensityPressure()*boost*dt;if(Math.random()<probability)reproduce(candidates[i],candidates[i+1],"grazer");}}
  LG.updateGrazers=(dt)=>{const c=SPECIES.grazer,seasonDrain=s.season==="winter"&&s.rules.fullSeasons?c.winterDrain:1;for(let i=s.grazers.length-1;i>=0;i-=1){const g=s.grazers[i];g.age+=dt;g.lastMealAge+=dt;g.energy-=c.baseDrain*seasonDrain*dt;g.reproductionCooldown=Math.max(0,g.reproductionCooldown-dt);const stage=LG.lifeStage(g),threat=LG.findNearest(g,s.hunters,c.threatRadius,h=>h.state!=="rest"&&h.state!=="feed");if(threat&&g.stamina>1){const angle=Math.atan2(g.y-threat.y,g.x-threat.x)+LG.randomBetween(-.18,.18),stageSpeed=stage==="juvenile"?.82:stage==="elder"?.84:1;LG.moveAnimal(g,angle,c.sprintSpeed*stageSpeed,dt);g.stamina=Math.max(0,g.stamina-c.staminaDrain*dt);g.energy-=c.sprintDrain*dt;}else{g.stamina=Math.min(c.staminaMax,g.stamina+c.staminaRecovery*dt);const p=chooseFoodPatch(g);if(p){const angle=Math.atan2(p.y-g.y,p.x-g.x),stageSpeed=stage==="juvenile"?.78:stage==="elder"?.82:1;LG.moveAnimal(g,angle,c.walkSpeed*stageSpeed,dt);const reach=p.radius*.72+9;if(LG.distanceSquared(g,p)<reach*reach){let eaten=0;if(p.green>.25){eaten=Math.min(p.green,c.eatRate*dt);p.green-=eaten;g.energy=Math.min(c.maxEnergy,g.energy+eaten*c.greenEnergy);LG.incrementMetric("greenConsumed",eaten);}else if(p.dry>.25){eaten=Math.min(p.dry,c.eatRate*.58*dt);p.dry-=eaten;g.energy=Math.min(c.maxEnergy,g.energy+eaten*c.dryEnergy);LG.incrementMetric("dryConsumed",eaten);}if(eaten>0)g.lastMealAge=0;}}else LG.wander(g,c.walkSpeed*.55,dt);}if(g.energy<=0)removeAnimal(s.grazers,i,"starvation");else if(oldAgeDeathChance(g,dt))removeAnimal(s.grazers,i,"oldAge");}attemptGrazerReproduction(dt);};

  function getHunterTarget(h){const existing=s.grazers.find(g=>g.id===h.targetId);if(existing&&LG.distanceSquared(h,existing)<=SPECIES.hunter.senseRadius**2)return existing;const next=LG.findNearest(h,s.grazers,SPECIES.hunter.senseRadius);h.targetId=next?.id??null;return next;}
  function consumeCarcass(h,c,dt){const amount=Math.min(c.biomass,34*dt);c.biomass-=amount;h.energy=Math.min(SPECIES.hunter.maxEnergy,h.energy+amount*SPECIES.hunter.carrionEnergy);h.lastMealAge=0;}
  function attemptHunt(h,prey){const c=SPECIES.hunter;h.attackCooldown=c.attackCooldown;LG.incrementMetric("huntAttempts");const preyStamina=prey.stamina/SPECIES.grazer.staminaMax,success=LG.clamp(.58+(h.energy/c.maxEnergy)*.12-preyStamina*.08+h.consecutiveFailures*.07,.42,.84);s.effects.push({kind:"lunge",x:h.x,y:h.y,age:0,color:"#8b70b7",angle:h.angle});if(Math.random()<success){const index=s.grazers.indexOf(prey);if(index>=0){s.grazers.splice(index,1);LG.createCarcass(prey.x,prey.y,"grazer",18);h.energy=Math.min(c.maxEnergy,h.energy+c.preyEnergy);h.lastMealAge=0;h.state="feed";h.stateTimer=c.feedRest;h.targetId=null;h.consecutiveFailures=0;LG.incrementMetric("grazerPredationDeaths");LG.incrementMetric("huntSuccesses");if(!s.eventFlags.firstHunt){s.eventFlags.firstHunt=true;LG.addEvent("猎食兽第一次成功扑杀食草兽，三层食物链开始真正运转。");}}}else{h.consecutiveFailures+=1;h.state="rest";h.stateTimer=c.restAfterMiss;LG.incrementMetric("huntFailures");}}
  function attemptHunterReproduction(dt){const c=SPECIES.hunter,season=LG.reproductionSeasonMultiplier();if(season<=0||s.hunters.length<2)return;const preyRatio=s.grazers.length/Math.max(1,s.hunters.length);if(preyRatio<4.5)return;const candidates=s.hunters.filter(a=>LG.lifeStage(a)==="adult"&&a.energy>=c.reproductionEnergy*.78&&a.reproductionCooldown<=0).sort((a,b)=>a.id-b.id);if(candidates.length<2||!candidates.some(a=>a.lastMealAge<=1.15))return;const boost=s.hunters.length<=2?2.5:1,probability=5*s.rules.fertility*season*hunterDensityPressure()*boost*dt;if(Math.random()<probability)reproduce(candidates[0],candidates[1],"hunter");}
  LG.updateHunters=(dt)=>{const c=SPECIES.hunter,seasonDrain=s.season==="winter"&&s.rules.fullSeasons?c.winterDrain:1;for(let i=s.hunters.length-1;i>=0;i-=1){const h=s.hunters[i];h.age+=dt;h.lastMealAge+=dt;h.energy-=c.baseDrain*seasonDrain*dt;h.reproductionCooldown=Math.max(0,h.reproductionCooldown-dt);h.attackCooldown=Math.max(0,h.attackCooldown-dt);const stage=LG.lifeStage(h);if(h.stateTimer>0){h.stateTimer-=dt;h.stamina=Math.min(c.staminaMax,h.stamina+c.staminaRecovery*1.3*dt);if(h.stateTimer<=0)h.state="wander";}else{const prey=getHunterTarget(h),carcass=LG.findNearest(h,s.carcasses,c.senseRadius*.72,item=>item.biomass>1),preyPerHunter=s.grazers.length/Math.max(1,s.hunters.length),allowHunt=preyPerHunter>3.5||h.energy<32;if(carcass&&h.energy<58){h.state="scavenge";h.stamina=Math.min(c.staminaMax,h.stamina+c.staminaRecovery*dt);const angle=Math.atan2(carcass.y-h.y,carcass.x-h.x);LG.moveAnimal(h,angle,c.walkSpeed,dt);if(LG.distanceSquared(h,carcass)<21*21)consumeCarcass(h,carcass,dt);}else if(prey&&allowHunt&&h.stamina>5){h.state="chase";const angle=Math.atan2(prey.y-h.y,prey.x-h.x),stageSpeed=stage==="elder"?.84:stage==="juvenile"?.8:1,distance=Math.sqrt(LG.distanceSquared(h,prey)),speed=distance<c.lungeDistance?c.lungeSpeed:c.chaseSpeed;LG.moveAnimal(h,angle,speed*stageSpeed,dt);h.stamina=Math.max(0,h.stamina-c.staminaDrain*dt);h.energy-=c.chaseDrain*dt;if(LG.distanceSquared(h,prey)<31*31&&h.attackCooldown<=0)attemptHunt(h,prey);}else if(carcass){h.state="scavenge";h.stamina=Math.min(c.staminaMax,h.stamina+c.staminaRecovery*dt);const angle=Math.atan2(carcass.y-h.y,carcass.x-h.x);LG.moveAnimal(h,angle,c.walkSpeed*.9,dt);if(LG.distanceSquared(h,carcass)<21*21)consumeCarcass(h,carcass,dt);}else{h.state="wander";h.targetId=null;h.stamina=Math.min(c.staminaMax,h.stamina+c.staminaRecovery*dt);LG.wander(h,c.walkSpeed*(stage==="elder"?.76:1),dt);}}if(h.energy<=0)removeAnimal(s.hunters,i,"starvation");else if(oldAgeDeathChance(h,dt))removeAnimal(s.hunters,i,"oldAge");}attemptHunterReproduction(dt);};

  LG.updateCarcasses=(dt)=>{for(let i=s.carcasses.length-1;i>=0;i-=1){const c=s.carcasses[i];c.age+=dt;const decomposed=Math.min(c.biomass,Math.max(1.7,c.biomass*1.35)*dt);c.biomass-=decomposed;LG.incrementMetric("carcassDecomposed",decomposed);const p=LG.findNearest(c,s.patches,115);if(p)p.fertility=LG.clamp(p.fertility+decomposed*.001,.35,1.3);if(c.biomass<=.35||c.age>=c.maxAge)s.carcasses.splice(i,1);}};

  LG.buildTrendSnapshot=()=>{const t=LG.getResourceTotals();return{year:s.year,flora:t.green,grazer:s.grazers.length,hunter:s.hunters.length};};
  function classifyTrend(current,previous,extinct=false){if(extinct)return"灭绝";const difference=current-previous,threshold=Math.max(1.2,Math.abs(previous)*.09);return difference>threshold?"上升":difference<-threshold?"下降":"稳定";}
  LG.updateTrends=()=>{if(!s.trendBaseline)s.trendBaseline=LG.buildTrendSnapshot();if(s.year-s.trendBaseline.year<WORLD.trendWindowYears)return;const current=LG.buildTrendSnapshot();s.trendValues={flora:classifyTrend(current.flora,s.trendBaseline.flora,!LG.hasDormantPlantLife()),grazer:classifyTrend(current.grazer,s.trendBaseline.grazer,current.grazer===0),hunter:classifyTrend(current.hunter,s.trendBaseline.hunter,current.hunter===0)};s.trendBaseline=current;};
  LG.missionCriteria=()=>{const noIntervention=!Number.isFinite(s.lastAnimalPlacementYear)||s.year-s.lastAnimalPlacementYear>=2,present=LG.getPresence();return{time:s.coexistenceYears>=WORLD.missionYears,grazerBirths:s.lifetime.grazerBirths>=8,hunterBirths:s.lifetime.hunterBirths>=2,hunts:s.lifetime.huntSuccesses>=5,spring:s.lifetime.springRecoveries>=2,noIntervention,minimums:s.minimumDuringAttempt.grazers>=3&&s.minimumDuringAttempt.hunters>=1,allPresent:present.flora&&present.grazer&&present.hunter};};
  LG.updateMission=(dt)=>{const present=LG.getPresence(),all=present.flora&&present.grazer&&present.hunter;if(all){s.coexistenceYears+=dt;s.longestCoexistence=Math.max(s.longestCoexistence,s.coexistenceYears);s.minimumDuringAttempt.grazers=Math.min(s.minimumDuringAttempt.grazers,s.grazers.length);s.minimumDuringAttempt.hunters=Math.min(s.minimumDuringAttempt.hunters,s.hunters.length);}else if(s.coexistenceYears>0){s.coexistenceYears=0;s.minimumDuringAttempt={grazers:s.grazers.length,hunters:s.hunters.length};}const complete=Object.values(LG.missionCriteria()).every(Boolean);if(complete&&!s.historicalMissionComplete){s.historicalMissionComplete=true;LG.addEvent("创世命题完成：这个世界已经证明三层生态能够自主捕食、繁殖并跨越四季。");LG.showToast?.("命题完成：三层生态已经形成自我延续闭环！",4200);}};
  function checkEndangered(){if(s.grazers.length>0&&s.grazers.length<=3&&!s.eventFlags.grazerEndangered){s.eventFlags.grazerEndangered=true;LG.addEvent("食草兽降至濒危线：剩余个体不足以稳定完成代际更新。");}if(s.grazers.length>5)s.eventFlags.grazerEndangered=false;if(s.hunters.length===1&&!s.eventFlags.hunterEndangered){s.eventFlags.hunterEndangered=true;LG.addEvent("猎食兽只剩1只，捕食层已无法通过配对繁殖延续。");}if(s.hunters.length>=2)s.eventFlags.hunterEndangered=false;}

  LG.calculateBalance=()=>{const totals=LG.getResourceTotals(),g=s.grazers.length,h=s.hunters.length,plant=LG.hasDormantPlantLife(),ga=LG.getAgeStructure(s.grazers),ha=LG.getAgeStructure(s.hunters);if(!plant&&g===0&&h===0)return{score:0,label:"生态崩溃",advice:"世界中已没有植物储备或动物。"};if(!plant)return{score:5,label:"生产者灭绝",advice:"草地、枯草和种子库都已耗尽。"};if(g===0&&h===0)return{score:18,label:"食物网崩解",advice:"植物仍然繁盛，但两级动物均已灭绝，完整生态无法自行恢复。"};if(g===0)return{score:12,label:"猎物断层",advice:"猎食兽仍然存在，但活体猎物已经消失。"};if(h===0){const score=LG.clamp(35+Math.min(18,g)-(s.trendValues.flora==="下降"?10:0),20,55);return{score,label:"捕食层缺失",advice:"食草兽和植物仍在运行，但没有猎食兽调节。"};}const reserve=totals.green+totals.dry*.45,reservePerGrazer=reserve/Math.max(1,g),preyPerHunter=g/h,huntRate=s.lifetime.huntAttempts?s.lifetime.huntSuccesses/s.lifetime.huntAttempts:0;let score=62;if(reservePerGrazer>=24&&reservePerGrazer<=75)score+=10;else if(reservePerGrazer<14)score-=20;else if(reservePerGrazer>115)score-=4;if(preyPerHunter>=5&&preyPerHunter<=12)score+=10;else if(preyPerHunter<3.5)score-=18;else if(preyPerHunter>18)score-=7;if(huntRate>=.35&&huntRate<=.72)score+=8;else if(s.lifetime.huntAttempts>=4&&huntRate<.2)score-=14;if(ga.juvenile>0&&ha.juvenile>0)score+=8;if(ha.adult===0||ga.adult===0)score-=18;if(s.trendValues.flora==="下降"&&s.trendValues.grazer==="上升")score-=12;score=LG.clamp(score,0,100);if(ha.adult===0||s.lifetime.hunterBirths===0)return{score:Math.min(score,65),label:"捕食层断代风险",advice:`猎食兽仍有${h}只，但尚未形成稳定后代；本局捕猎成功${s.lifetime.huntSuccesses}次。`};if(reservePerGrazer<16)return{score,label:"食物压力升高",advice:`每只食草兽可用植物储备约${reservePerGrazer.toFixed(1)}。`};return score>=82?{score,label:"周期性平衡",advice:"三层生态都在完成代际更新，资源、猎物和捕食者处于可恢复波动中。"}:{score,label:"脆弱但完整",advice:"三层结构仍存在，但代际、捕猎效率或资源储备中至少一项接近风险区。"};};

  LG.updateWorld=(dt)=>{const previous=s.year;s.year+=dt;LG.rolloverLedgerIfNeeded(previous);LG.updateSeason();LG.updatePatches(dt);LG.updateGrazers(dt);LG.updateHunters(dt);LG.updateCarcasses(dt);LG.checkPresenceChanges();checkEndangered();LG.updateMission(dt);LG.updateTrends();};
})();
